### ISSUE TITLE
406 Shopify Error on Install

### ISSUE THREAD

**Issue by bendrobinson1998** [kinngh/shopify-node-express-mongodb-app#128]
The app is deployed in production on Heroku, build succeeds with no errors. 

Upon visiting the install url I am met with the app install button, when I press it I am taken to a page displaying this error: 

```
2024-05-10T10:33:39.749537+00:00 app[web.1]: ---> Error at /api/auth/tokens HttpResponseError: Received an error response (406 Not Acceptable) from Shopify:
2024-05-10T10:33:39.749584+00:00 app[web.1]: {
2024-05-10T10:33:39.749585+00:00 app[web.1]: "networkStatusCode": 406,
2024-05-10T10:33:39.749586+00:00 app[web.1]: "message": "GraphQL Client: Not Acceptable",
2024-05-10T10:33:39.749587+00:00 app[web.1]: "response": {
2024-05-10T10:33:39.749587+00:00 app[web.1]: "size": 0,
2024-05-10T10:33:39.749597+00:00 app[web.1]: "timeout": 0
2024-05-10T10:33:39.749597+00:00 app[web.1]: }
2024-05-10T10:33:39.749597+00:00 app[web.1]: }
2024-05-10T10:33:39.749597+00:00 app[web.1]: If you report this error, please include this id: *******
2024-05-10T10:33:39.749599+00:00 app[web.1]: at throwFailedRequest (/app/node_modules/@shopify/shopify-api/lib/clients/common.js:108:19)
2024-05-10T10:33:39.749600+00:00 app[web.1]: at NewGraphqlClient.request (/app/node_modules/@shopify/shopify-api/lib/clients/admin/graphql/client.js:67:45)
2024-05-10T10:33:39.749600+00:00 app[web.1]: at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-05-10T10:33:39.749600+00:00 app[web.1]: at async getExistingHandlers (/app/node_modules/@shopify/shopify-api/lib/webhooks/register.js:65:26)
2024-05-10T10:33:39.749600+00:00 app[web.1]: at async Object.register (/app/node_modules/@shopify/shopify-api/lib/webhooks/register.js:19:34)
2024-05-10T10:33:39.749601+00:00 app[web.1]: at async file:///app/server/middleware/auth.js:66:39 {
2024-05-10T10:33:39.749601+00:00 app[web.1]: response: {
2024-05-10T10:33:39.749602+00:00 app[web.1]: code: 406,
2024-05-10T10:33:39.749602+00:00 app[web.1]: statusText: 'Not Acceptable',
2024-05-10T10:33:39.749602+00:00 app[web.1]: body: { errors: [Object] },
2024-05-10T10:33:39.749602+00:00 app[web.1]: headers: {
2024-05-10T10:33:39.749602+00:00 app[web.1]: 'Alt-Svc': [Array],
2024-05-10T10:33:39.749602+00:00 app[web.1]: 'Cf-Cache-Status': [Array],
2024-05-10T10:33:39.749603+00:00 app[web.1]: 'Cf-Ray': [Array],
2024-05-10T10:33:39.749603+00:00 app[web.1]: Connection: [Array],
2024-05-10T10:33:39.749603+00:00 app[web.1]: 'Content-Security-Policy': [Array],
2024-05-10T10:33:39.749603+00:00 app[web.1]: 'Content-Type': [Array],
2024-05-10T10:33:39.749603+00:00 app[web.1]: Date: [Array],
2024-05-10T10:33:39.749603+00:00 app[web.1]: Http_x_shopify_shop_api_call_limit: [Array],
2024-05-10T10:33:39.749604+00:00 app[web.1]: Nel: [Array],
2024-05-10T10:33:39.749604+00:00 app[web.1]: 'Referrer-Policy': [Array],
2024-05-10T10:33:39.749604+00:00 app[web.1]: 'Report-To': [Array],
2024-05-10T10:33:39.749604+00:00 app[web.1]: Server: [Array],
2024-05-10T10:33:39.749604+00:00 app[web.1]: 'Server-Timing': [Array],
2024-05-10T10:33:39.749604+00:00 app[web.1]: 'Strict-Transport-Security': [Array],
2024-05-10T10:33:39.749604+00:00 app[web.1]: 'Transfer-Encoding': [Array],
2024-05-10T10:33:39.749605+00:00 app[web.1]: 'X-Content-Type-Options': [Array],
2024-05-10T10:33:39.749605+00:00 app[web.1]: 'X-Dc': [Array],
2024-05-10T10:33:39.749605+00:00 app[web.1]: 'X-Download-Options': [Array],
2024-05-10T10:33:39.749605+00:00 app[web.1]: 'X-Frame-Options': [Array],
2024-05-10T10:33:39.749605+00:00 app[web.1]: 'X-Permitted-Cross-Domain-Policies': [Array],
2024-05-10T10:33:39.749605+00:00 app[web.1]: 'X-Request-Id': [Array],
2024-05-10T10:33:39.749606+00:00 app[web.1]: 'X-Shardid': [Array],
2024-05-10T10:33:39.749606+00:00 app[web.1]: 'X-Shopid': [Array],
2024-05-10T10:33:39.749606+00:00 app[web.1]: 'X-Shopify-Api-Version': [Array],
2024-05-10T10:33:39.749606+00:00 app[web.1]: 'X-Shopify-Shop-Api-Call-Limit': [Array],
2024-05-10T10:33:39.749606+00:00 app[web.1]: 'X-Sorting-Hat-Podid': [Array],
2024-05-10T10:33:39.749606+00:00 app[web.1]: 'X-Sorting-Hat-Shopid': [Array],
2024-05-10T10:33:39.749607+00:00 app[web.1]: 'X-Stats-Apiclientid': [Array],
2024-05-10T10:33:39.749607+00:00 app[web.1]: 'X-Stats-Apipermissionid': [Array],
2024-05-10T10:33:39.749607+00:00 app[web.1]: 'X-Stats-Userid': [Array],
2024-05-10T10:33:39.749607+00:00 app[web.1]: 'X-Xss-Protection': [Array]
2024-05-10T10:33:39.749607+00:00 app[web.1]: }
2024-05-10T10:33:39.749607+00:00 app[web.1]: }
2024-05-10T10:33:39.749607+00:00 app[web.1]: }
```

I have not modified the auth.js file or server/index.js file.

If I refresh the page after being met with this error the app loads fine but loop redirects to the token page on all routes.

**Comment by bendrobinson1998** [comment]
Closing, resolved found fix here: [](https://github.com/kinngh/shopify-node-express-mongodb-app/discussions/74)
