### ISSUE TITLE
Deplyoment error 

### ISSUE THREAD

**Issue by klocguru** [kinngh/shopify-node-express-mongodb-app#37]
Error: ENOENT: no such file or directory, open '/app/frontend/dist/index.html'
    at Object.openSync (node:fs:590:3)
    at readFileSync (node:fs:458:35)
    at file:///app/server/index.js:182:15
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
    at /app/node_modules/express/lib/router/index.js:286:9
    at param (/app/node_modules/express/lib/router/index.js:365:14)
    at param (/app/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/app/node_modules/express/lib/router/index.js:421:3)
    at next (/app/node_modules/express/lib/router/index.js:280:10)
    at SendStream.error (/app/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (node:events:513:28)
    at SendStream.error (/app/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/app/node_modules/send/index.js:417:12)
    at onstat (/app/node_modules/send/index.js:722:26)
    at FSReqCallback.oncomplete (node:fs:202:21)

Hi,
I m getting this error after the deployment, can you please help to fix it?
Thank You!

**Comment by kinngh** [comment]
You need to run "npm run build" before you deploy.

**Comment by Gitgcs** [comment]
Thank you so much!
