### ISSUE TITLE
app not loading due to  app.post("/graphql", verifyRequest  

### ISSUE THREAD

**Issue by adventuretocode** [kinngh/shopify-node-express-mongodb-app#44]
i am getting error 

app was ruining perfectly  but  few store  can't access the app pages

app is working fine there is no any change code based or package version  - some case from store or may be shopify 

code was still this repo up to date 

https://github.com/kinngh/shopify-node-express-mongodb-app/commit/6919b8f880bf096ba6914e791ca5fcf6d1c6f098

`@shopify/shopify-api": "^5.2.0",`
Here is app log
`  data: { appInstallation: null },
   errors: [ { message: 'access denied', locations: [Array], path: [Array] } ],
   extensions: {
     cost: {
       requestedQueryCost: 14,
       actualQueryCost: 2,
       throttleStatus: [Object]
     }
   }
 }
 InvalidJwtError: Failed to parse session token 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpxxxxxxxxx1wvdHJ5LXNob3AtZm9yLXRlc3QubXlzaG9waWZ5LmNvbVwvYWRtaW4iLCJkZXN0IjoiaHR0cHM6XC9xxxxxxxxxxx5c2hvcGlmeS5jb20iLCJhdWQiOiI4ODgwM2U5MDdmZDM5MmEzZTlmNzJmNDBmYzJlMTRhYyIsInN1YiI6IjgxMDUwNjk3OTMzIiwiZXhwIjoxNjczODY2MDYwLCJuYmYiOjE2NzM4NjYwMDAsImlhdCI6MTY3Mzg2NjAwMCwianRpIjoiYzY3NzY2YmUtMTljMy00ZjM3LxxxxxxxxxxxxxxTZkNTRmMGQyIiwic2lkIjoiMGU2MzhlYTc2N2RlMDFiYTJkMDA4M2FhNmFjZDJlMmYwMDFkZTEzNDY5NzUxYzYyZTFkZTM5M2IyZWMzZTVkYiJ9.srz83D65MJZajDYSg-vnms5xxxxxxxkIQo-j5arrKn0': jwt expired
     at InvalidJwtError.ShopifyError [as constructor] (appcode/node_modules/@shopify/shopify-api/dist/error.js:13:28)
     at new InvalidJwtError (appcode/node_modules/@shopify/shopify-api/dist/error.js:47:42)
     at decodeSessionToken (appcode/node_modules/@shopify/shopify-api/dist/utils/decode-session-token.js:23:15)
     at Object.getCurrentSessionId (appcode/node_modules/@shopify/shopify-api/dist/auth/oauth/oauth.js:174:69)
     at Object.<anonymous> (appcode/node_modules/@shopify/shopify-api/dist/utils/load-current-session.js:19:46)
     at step (appcode/node_modules/tslib/tslib.js:144:27)
     at Object.next (appcode/node_modules/tslib/tslib.j`
     
     
     today i am access  app  successfully with my store and one client  store.
     Network call Success call store 
 
![app gql working Screenshot](https://user-images.githubusercontent.com/114073623/212680854-e7b86bb4-f6a2-4496-a5d9-88c1eb60279f.png)

     one store i found the app page not loading due to the graphQL call fails 
    Network call  fails store  call
      
![Screenshot from 2023-01-16 18-05-14 gql fail](https://user-images.githubusercontent.com/114073623/212680184-45ee4840-47c1-438d-bcc3-63190485460f.png)

Test case
-  fails user app installed more then one week 
- tested app with fresh new install new store not any error it's working fine. 
- for the session token update i force enter the /auth it was successfully db updated but still getting same error

**Comment by adventuretocode** [comment]
this issue not related to the this code based
